### ISSUE TITLE
Feature request: Enable EFI_RT_VOLATILE_STORE

### ISSUE THREAD

**Issue by NN708** [inindev/uboot-rockchip#3]
When installing Fedora Rawhide via UEFI on U-Boot, the installation fails to write boot loader configuration ([details](https://bugzilla.redhat.com/show_bug.cgi?id=2333190)). The cause is that `/sys/firmware/efi/efivars` is mounted as read-only. Attempts to remount it fail with the error: "Firmware does not support SetVariableRT. Cannot remount with rw".

Further investigation reveals that [a patch](https://lore.kernel.org/u-boot/20240406140203.248211-1-ilias.apalodimas@linaro.org/) was already merged, which introduces `EFI_RT_VOLATILE_STORE` config option. But currently, this feature is not enabled by default in board configurations. Could this be enabled to ensure successful OS installation?

**Comment by inindev** [comment]
I can cherry-pick this in, but I am not seeing it in master yet.  The first patch in the series modifies lib/efi_loader/efi_runtime.c but I am not seeing this change int the repo: https://github.com/u-boot/u-boot/commits/master/lib/efi_loader/efi_runtime.c

**Comment by NN708** [comment]
> The first patch in the series modifies lib/efi_loader/efi_runtime.c but I am not seeing this change int the repo: https://github.com/u-boot/u-boot/commits/master/lib/efi_loader/efi_runtime.c

The commit is https://github.com/u-boot/u-boot/commit/c28d32f946f0d1c0780a02ab49dc2c1835370501.

**Comment by inindev** [comment]
Which board are you able to test this on?

**Comment by NN708** [comment]
I can test this on the ROCK 5B board.

**Comment by inindev** [comment]
I regret the delay; the cherry-pick build was complicated by multiple commit dependencies that grew complex.
I just published the 2025.07-rc2 pre-release which will have this commit.

**Comment by inindev** [comment]
https://github.com/inindev/uboot-rockchip/releases/tag/v2025.07-rc3

**Comment by NN708** [comment]
Thank you for your help! I have tested `v2025.07-rc3` on the ROCK 5B, but unfortunately, the issue still persists.
